### ISSUE TITLE
Nothing's here! (Todo List)

### ISSUE THREAD

**Issue by Bault496** [Bault496/MMO-Gear-Comparison-App#1]
Making a todo list/planning a bit.

Objective of the app is so people can input their character and different gear choices and figure out which gear is better for which character.

Issues that need to be made:
Create Character Class
Create Role Class
Create Gear Class
Compare Gear to Gear functionality

**Comment by davischristianson** [comment]
# Todo list/ideas

Create Gear Attributes (Info to display to user)
Create a possible way to export data as a pdf for the user to keep
Possible save option for a configuration of class + gears


Possible template idea
- Create possible explanation on stats either on hover of a stat or on a separate page
- Create class templates and possible classes to choose from
    - Classes could affect how stats work with that class
         - Ex. One gear could have better stats overall but not be as good for one class as it would be for another one
- Create a way to store pictures and show gear appearance 
- Maybe have gear comparisons for multiple games (could be a lot of work due to entering information)
- Include gear rarity, common, uncommon, rare, epic, legendarty etc.
- Add colors to enhance UI and engagement

**Comment by davischristianson** [comment]
# Examples of a possible templates to use
## World of Warcraft example
 
- WoW class template example `https://wowpedia.fandom.com/wiki/Class`
     - Death Knight
         - Tank 
         - Melee Physical/Magic Damage Dealer
     - Demon hunter
         - Melee Physical Damage Dealer 
         - Tank
     - Druid
         - Ranged Spell-Casting Damage Dealer
         - Melee Physical Damage Dealer
         - Tank
         - Healer
     - Evoker
         - Ranged Spell-Casting Damage Dealer
         - Healer
     - Hunter
         - Ranged Physical Damage Dealer
         - Melee Physical Damage Dealer
     - Mage
         - Ranged Spell-Casting Damage Dealer
     - Monk
         - Melee Physical Damage Dealer
         - Tank
         - Healer
     - Paladin
         - Melee Physical/Magic Damage Dealer
         - Tank
         - Healer
     - Priest
         - Healer 
         - Ranged Spell-Casting Damage Dealer
     - Rogue
         - Melee Physical Damage Dealer
     - Shaman
         - Ranged Spell-Casting Damage Dealer 
         - Melee Physical/Magic Damage Dealer 
         - Healer
     - Warlock
         - Ranged Spell-Casting Damage Dealer
     - Warrior
         - Melee Physical Damage Dealer 
         - Tank

- WoW gear attribute template example `https://wowpedia.fandom.com/wiki/Attributes`
    - Primary attributes/stats
         - Strength
         - Agility
         - Intellect 
         - Stamina
    - Secondary attributes/stats
         - Critical Strike
         - Haste
         - Mastery
         - Versatility
    - Tertiary attributes/stats
         - Avoidance
         - Indestructible
         - Leech
         - Speed
    - Derived combat attributes
         - Physical
             - Attack power (AP)
             - Attack speed 
             - Melee/ranged critical strike
         - Spell
             - Spell power
             - Casting speed
             - Mana Regeneration
             - Spell critical strike
         - Defense
             - Armor
             - Dodge
             - Parry
             - Block

**Comment by davischristianson** [comment]
# Examples of a possible templates to use
## Final Fantasy 14 example

- FF14 class template example `https://na.finalfantasyxiv.com/a_realm_reborn/game/#!/classes`
    - Disciples of War
        - Gladiator
        - Pugilist
        - Marauder
        - Lancer
        - Archer
        - Rogue
    - Disciples of Magic
        - Conjurer
        - Thaumaturge 
        - Arcanist
    - Disciples of the Hand
        - Carpenter
        - Blacksmith
        - Armorer
        - Goldsmith
        - Leatherworker
        - Weaver
        - Alchemist
        - Culinarian
    - Disciples of the Land
        - Miner
        - Botanist
        - Fisher

- FF14 job template example `https://na.finalfantasyxiv.com/a_realm_reborn/game/#!/jobs`
    - Paladin
    - Monk
    - Warrior
    - Bard
    - White Mage
    - Black Mage
    - Summoner
    - Scholar
    - Ninja

- FF14 stat/attribute template example `https://ffxiv.consolegameswiki.com/wiki/Attributes`
    - Attributes
        - Strength
        - Dexterity
        - Vitality
        - Intelligence
        - Mind
    - Points
        - HP (Health points)
        - MP (Magic points)
    - Meldable stats (substats)
        - Critical Hit
        - Determination
        - Direct Hit Rate
        - Skill Speed
        - Spell Speed
    - Role
        - Tenacity
        - Piety
    - Other properties
        - Attack Power
        - Attack Magic Potency
        - Healing Magic Potency
        - Defense
        - Magic Defense

**Comment by davischristianson** [comment]
# WoW gear layout 
- Layout example
![wnq15rxxpg841](https://github.com/Bault496/MMO-Gear-Comparison-App/assets/131329691/1edce68b-b107-4dfc-b55e-355a8de5d3a4)

- Hover over gear to show stats and info
![uvOxG1Y](https://github.com/Bault496/MMO-Gear-Comparison-App/assets/131329691/9c2cf6b3-27dc-45c4-87e7-cf1c55ac30fb)

**Comment by davischristianson** [comment]
# FF14 gear layout
- Layout example
![a0f80358a284600995db17145969f3762855ed](https://github.com/Bault496/MMO-Gear-Comparison-App/assets/131329691/ca0c0e00-8b2e-4501-ba5d-9178673325ed)
